### ISSUE TITLE
Cannot import KW47-EVK from mcuxpresso sdk

### ISSUE THREAD

**Issue by yvesll** [nxp-mcuxpresso/vscode-for-mcux#82]
## Environment
OS Build: Windows 11 Enterprise 22631.5335
VSCode Version: 1.100.2
Extension Version: 25.5.20
SDK Version: v25.06.00-pvw2

## How to Reproduce

![Image](https://github.com/user-attachments/assets/64494ad3-8389-4f94-a96f-731d1102353f)
When select KW47-EVK, the plugin will popup an error and not able to select any example.

**Comment by cristitep-nxp** [comment]
Hi @yvesll ,

We confirm the issue, there is a problem in a project definition. Until the problem will be fixed, please:
1. go to SDK repository in <repo>\mcuxsdk\examples\wireless_examples\ble_controller\nbu_ble
2. edit example.yml
3. instead of:
```
boards:
    kw47evk@cm33_core1:
    mcxw72evk@cm33_core1:
    frdmmcxw72@cm33_core1:
    kw43evk_nbu:
    kw45b41zevk_nbu:
    - -armgcc@debug
    - -armgcc@release
```
write:
```
boards:
    kw47evk@cm33_core1:[]
    mcxw72evk@cm33_core1: []
    frdmmcxw72@cm33_core1: []
    kw43evk_nbu: []
    kw45b41zevk_nbu:
    - -armgcc@debug
    - -armgcc@release
```
4. reopen Import Example view and retry loading that board

Regards,
Cristian
